version: '3.9'

services:

  db:
    image: postgres:14
    container_name: postgres
    restart: always     
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    networks:
      - skynet
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - skynet

  app:
    container_name: tetris-app
    image: tetris-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      SERVER_PORT: ${SERVER_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
    depends_on:
      - db
    networks:
      - skynet

  nginx:
    container_name: nginx
    image: nginx
    build:
      dockerfile: Dockerfile.nginx
    restart: always
    depends_on:
      - app
      - db
    ports:
      - "80:80"
      - "443:443"
    networks:
      - skynet  

networks:
    skynet:
        driver: bridge
